# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f45959c53063825ba18b07e06939166dca38034f8ab80b4a15412d760e6ff09f471dc97fc34c4755259285d951a0c04ebd431793c25026b687d78da5ef8a47be

test:
  secret_key_base: 22df30ddd145da80fb6a4f6b219791d849169d88e9651c2aa172dc94f3d4add2fd8cfe9e0cd09013033089c861e788741edef0d9460230f7cd2a3de8db1599e0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
